const KEY='baby-growth-v1';
const defaults={tasks:[
  {id:'reading',name:'阅读 20 分钟',category:'学习',emoji:'📚'},
  {id:'homework',name:'认真完成作业',category:'学习',emoji:'✏️'},
  {id:'tidy',name:'收拾自己的物品',category:'生活习惯',emoji:'🧸'},
  {id:'manners',name:'礼貌表达，好好说话',category:'品德',emoji:'💛'},
  {id:'exercise',name:'运动 30 分钟',category:'健康',emoji:'⚽'}
],rewards:[{id:'park',name:'去一次喜欢的公园',cost:60,emoji:'🛝'},{id:'movie',name:'周末电影之夜',cost:100,emoji:'🍿'}],records:[],notes:[]};
let data=load(), selectedTask=null, shownMonth=new Date();
const $=s=>document.querySelector(s), todayKey=()=>new Date().toISOString().slice(0,10);
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY))}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dateCN(d=new Date()){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(d)}
function points(){return data.records.reduce((sum,r)=>sum+r.points,0)}
function dateRecords(day){return data.records.filter(r=>r.date===day)}
function scoreText(r){return r.score==='good'?'做得很棒':r.score==='okay'?'基本完成':'需要提醒'}
function render(){
  $('#todayLabel').textContent=dateCN(); $('#points').textContent=weekRecords().reduce((s,r)=>s+r.points,0); $('#totalPoints').textContent=points();
  $('#weekMessage').textContent=points()>0?'小星星正在一点点积累':'每一次认真，都值得被看见'; renderTasks();renderRecent();renderRewards();renderStats();
}
function renderTasks(){const today=todayKey();$('#taskList').innerHTML=data.tasks.map(t=>{const r=dateRecords(today).find(x=>x.taskId===t.id);return `<article class="task ${r?'task-done':''}"><div class="emoji">${t.emoji}</div><div class="task-info"><h3>${esc(t.name)}</h3><p>${esc(t.category)} · ${r?scoreText(r):'还没有评分'}</p></div><button class="score-status" data-score="${t.id}">${r?(r.points>0?`+${r.points} 分`:`${r.points} 分`):'去评分'}</button></article>`}).join('')||'<p class="empty">还没有考核项目，添加一个吧。</p>';document.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>openScore(b.dataset.score))}
function renderRecent(){const items=[...data.records.map(r=>({type:'score',...r})),...data.notes.map(n=>({type:'note',...n}))].sort((a,b)=>b.created-a.created).slice(0,5);$('#recentList').innerHTML=items.length?items.map(item=>item.type==='note'?`<div class="record"><span>${item.date.slice(5).replace('-','月')}日</span><span>📝 ${esc(item.text)}</span></div>`:`<div class="record"><span>${item.date.slice(5).replace('-','月')}日</span><span>${esc(item.taskName)} · ${scoreText(item)}</span><b>${item.points>0?'+':''}${item.points} 分</b></div>`).join(''):'<p class="empty">今天还没有记录。</p>'}
function renderRewards(){$('#rewardList').innerHTML=data.rewards.map(r=>`<article class="reward"><div class="reward-icon">${r.emoji}</div><div><h3>${esc(r.name)}</h3><p>需要 ${r.cost} 分 · 现有 ${points()} 分</p></div><button class="redeem" data-redeem="${r.id}" ${points()<r.cost?'disabled':''}>兑换</button></article>`).join('')||'<p class="empty">先添加一个小心愿吧。</p>';document.querySelectorAll('[data-redeem]').forEach(b=>b.onclick=()=>redeem(b.dataset.redeem))}
function weekStart(){const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}
function weekRecords(){const start=weekStart();return data.records.filter(r=>new Date(r.date+'T00:00:00')>=start)}
function renderStats(){const wr=weekRecords();$('#weekDone').textContent=wr.filter(r=>r.points>0).length;$('#streak').textContent=calcStreak();renderCalendar();const cats={};wr.forEach(r=>{if(r.points>0)cats[r.category]=(cats[r.category]||0)+1});const max=Math.max(...Object.values(cats),1);$('#categoryStats').innerHTML=Object.keys(cats).length?Object.entries(cats).map(([name,n])=>`<div class="category-row"><span>${esc(name)}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join(''):'<p class="empty">本周还没有好表现记录。</p>'}
function calcStreak(){let n=0,d=new Date();while(true){const key=d.toISOString().slice(0,10);if(dateRecords(key).some(r=>r.points>0)){n++;d.setDate(d.getDate()-1)}else break}return n}
function renderCalendar(){const y=shownMonth.getFullYear(),m=shownMonth.getMonth();$('#monthTitle').textContent=`${y}年${m+1}月`;const first=new Date(y,m,1), last=new Date(y,m+1,0), offset=(first.getDay()+6)%7, days=last.getDate(), now=todayKey();let html='';for(let i=0;i<offset;i++)html+='<span class="dim"></span>';for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`, good=dateRecords(key).some(r=>r.points>0);html+=`<span class="${good?'marked':''} ${key===now?'today':''}">${d}</span>`}$('#calendar').innerHTML=html}
function openScore(id){selectedTask=data.tasks.find(t=>t.id===id);const old=dateRecords(todayKey()).find(r=>r.taskId===id);if(old){if(confirm(`“${selectedTask.name}”今天已评分为「${scoreText(old)}」。要重新评分吗？`))data.records=data.records.filter(r=>r!==old);else return}$('#scoreCategory').textContent=selectedTask.category;$('#scoreTitle').textContent=selectedTask.name;$('#scoreDialog').showModal()}
$('#scoreDialog').addEventListener('close',()=>{const v=$('#scoreDialog').returnValue;if(['good','okay','bad'].includes(v)&&selectedTask){const p={good:5,okay:2,bad:-2}[v];data.records.push({id:crypto.randomUUID(),taskId:selectedTask.id,taskName:selectedTask.name,category:selectedTask.category,date:todayKey(),score:v,points:p,created:Date.now()});save()}})
function openForm(type){const dialog=$('#formDialog'), fields=$('#formFields');dialog.dataset.type=type;$('#formTitle').textContent=type==='task'?'添加考核项目':type==='reward'?'添加心愿奖励':'写下今天的记录';if(type==='task')fields.innerHTML='<label>项目名称<input name="name" required placeholder="例如：按时刷牙" /></label><label>分类<select name="category"><option>学习</option><option>生活习惯</option><option>品德</option><option>健康</option><option>其他</option></select></label><label>图标（可选）<input name="emoji" value="🌟" maxlength="2" /></label>';else if(type==='reward')fields.innerHTML='<label>心愿名称<input name="name" required placeholder="例如：买一本喜欢的书" /></label><label>需要积分<input name="cost" type="number" min="1" value="50" required /></label><label>图标（可选）<input name="emoji" value="🎁" maxlength="2" /></label>';else fields.innerHTML='<label>今天的记录<textarea name="note" required placeholder="例如：主动帮忙摆好餐具，值得表扬。"></textarea></label>';dialog.showModal()}
$('#entryForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),type=$('#formDialog').dataset.type;if(type==='task')data.tasks.push({id:crypto.randomUUID(),name:fd.get('name'),category:fd.get('category'),emoji:fd.get('emoji')||'🌟'});if(type==='reward')data.rewards.push({id:crypto.randomUUID(),name:fd.get('name'),cost:Number(fd.get('cost')),emoji:fd.get('emoji')||'🎁'});if(type==='note')data.notes.push({id:crypto.randomUUID(),date:todayKey(),text:fd.get('note'),created:Date.now()});$('#formDialog').close();e.target.reset();save()};
$('#closeForm').onclick=()=>$('#formDialog').close();$('#addTaskBtn').onclick=()=>openForm('task');$('#addRewardBtn').onclick=()=>openForm('reward');$('#addNoteBtn').onclick=()=>openForm('note');
function redeem(id){const r=data.rewards.find(r=>r.id===id);if(confirm(`确定兑换「${r.name}」吗？将扣除 ${r.cost} 分。`)){data.records.push({id:crypto.randomUUID(),taskId:'reward',taskName:`兑换：${r.name}`,category:'奖励兑换',date:todayKey(),score:'reward',points:-r.cost,created:Date.now()});save();alert('兑换成功！别忘了兑现和孩子的约定。')}}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.view).classList.add('active')});
$('#prevMonth').onclick=()=>{shownMonth.setMonth(shownMonth.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{shownMonth.setMonth(shownMonth.getMonth()+1);renderCalendar()};
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`小芽成长备份-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!Array.isArray(incoming.tasks)||!Array.isArray(incoming.records))throw Error();if(confirm('导入会覆盖当前本机数据，确定继续吗？')){data={...defaults,...incoming};save();alert('已导入备份。')}}catch{alert('这个备份文件无法识别。')}};reader.readAsText(f);e.target.value=''};
$('#settingsBtn').onclick=()=>alert('小芽成长\n\n这是一个完全离线的小工具。\n数据保存于这台设备的浏览器中，请定期在“成长记录”导出备份。');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
